{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "splunk-k8s-win-logging.fullname" . }}
  labels:
    app: {{ template "splunk-k8s-win-logging.name" . }}
    chart: {{ template "splunk-k8s-win-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "splunk-k8s-win-logging.fullname" . }}]
{{- end }}
- apiGroups:
    - ""
  resources:
    - "namespaces"
    - "pods"
  verbs:
    - "list"
    - "get"
    - "watch"
{{- end -}}