{{- if .Values.serviceAccount.create -}}
apiVersion: v1
{{ if .Values.image.usePullSecret }}
imagePullSecrets:
- name: {{ .Values.image.pullSecretName }}
{{ end }}
kind: ServiceAccount
metadata:
  name: {{ template "splunk-k8s-win-logging.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-k8s-win-logging.name" . }}
    chart: {{ template "splunk-k8s-win-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
  